@extends('layouts.app')
@php
$pages = [
 'accounts' => ['Accounts','Accounts designed around everyday needs','Choose clear, flexible account options for the way you manage money.', [['Savings account','Save and manage your money with flexible account access.'],['Current account','Practical banking solutions for everyday financial management.'],['Account summary','View account details and a consolidated transaction history.'],['Fixed deposits','Explore structured savings choices for your financial goals.']]],
 'cards' => ['Cards','Find a credit card that fits your lifestyle','Choose from everyday convenience, travel privileges and premium experiences.', [['FinBank Classic','Everyday rewards, shopping benefits and easy account management.'],['FinBank Platinum','Travel, dining and lifestyle privileges.'],['FinBank Signature','Premium features and enhanced experiences.']]],
 'loans' => ['Loans','Loans designed around your goals','Explore financing for life’s important moments without complicated language.', [['Personal loan','Financial flexibility when you need it.'],['Home loan','Take the next step toward your future home.'],['Car loan','Finance your next journey with flexible options.'],['Education loan','Support the learning goals that shape your future.'],['Business loan','Explore finance designed around business ambitions.']]],
 'offers' => ['Offers','Featured offers','Discover benefits designed around dining, travel, shopping and your lifestyle.', [['Shopping rewards','Make everyday purchases more rewarding.'],['Dining benefits','Enjoy selected benefits with participating dining experiences.'],['Travel benefits','Discover privileges available with eligible FinBank products.'],['Lifestyle benefits','Explore experiences designed around the way you live.']]],
 'digital' => ['Digital Banking','Banking at your fingertips','Manage your finances from wherever you are with clear, convenient account access.', [['Secure sign-in','Access your account with its account number and PIN.'],['Fund management','Deposit, withdraw and transfer funds.'],['Transaction history','Review account activity in one clear view.'],['PIN management','Update the PIN for your signed-in account.']]],
 'security' => ['Security','Security at every step','Practical safeguards support your privacy and online account access.', [['Protected sessions','Account tools require a signed-in application session.'],['Safer database access','Parameterized operations help protect account requests.'],['Controlled visibility','Account tools use the account stored in your current session.'],['Account privacy','Sensitive access stays behind authentication.']]],
]; $content = $pages[$page];
@endphp
@section('title', $content[0].' — FinBank')
@section('description', $content[2])
@section('content')
<header class="page-hero"><div class="container"><span class="eyebrow">FinBank {{ $content[0] }}</span><h1>{{ $content[1] }}</h1><p>{{ $content[2] }}</p></div></header>
<section class="section"><div class="container"><div class="row g-4">@foreach ($content[3] as $index => $item)<div class="col-md-6"><article class="product-card"><div class="icon-tile">{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</div><h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p><a href="{{ url('/contact') }}" class="text-link">Learn more →</a></article></div>@endforeach</div><div class="text-center mt-5"><a href="{{ url('/contact') }}" class="btn primary-btn btn-dark">Talk to FinBank</a></div></div></section>
@endsection
